import prisma from "@/db";

type InterviewDetails = {
  topic: string;
  role: string;
  yearsOfExperience: string;
  duration: string;
};

interface Question {
  question: string; // The question text generated by the AI
  correctAnswer: string; // The correct answer provided by the AI
}

interface GenerateQuestionsResponse {
  questions: Question[]; // Array of questions generated by the AI
}

export async function saveQuestionsToDB(
  generateQuestions: GenerateQuestionsResponse,
  interviewDetails: InterviewDetails
) {
  // const Questionata = await prisma.interview.create({
  //   data: {
  //     topic: interviewDetails.topic,
  //     role: interviewDetails.role,
  //     experience: interviewDetails.yearsOfExperience,
  //     duration: interviewDetails.duration,
  //     userId       String      // Foreign key reference to User
  //     user         User        @relation(fields: [userId], references: [id], onDelete: Cascade)
  //   },
  // });
}
